# Generated by Django 3.2.9 on 2021-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=50)),
                ('expansion_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('fine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('restriction_start_time', models.TimeField()),
                ('restriction_end_time', models.TimeField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
