# Generated by Django 3.2.9 on 2021-11-13 13:04

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('meter_reading_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.room')),
                ('water', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('heating', models.IntegerField()),
                ('review_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.card')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None)),
            ],
        ),
    ]
