# Generated by Django 3.2.9 on 2021-11-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_meterreading_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.user')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.room')),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('fingerprint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.user')),
                ('data', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.user')),
                ('job', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.user')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.room')),
                ('course', models.IntegerField()),
            ],
        ),
    ]
