# Generated by Django 3.2.9 on 2021-11-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_access_fingerprint_staff_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fingerprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.fingerprint')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.sensor')),
                ('scan_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('penalty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.student')),
                ('fine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.fine')),
                ('return_time', models.DateTimeField()),
            ],
        ),
    ]
