# Generated by Django 3.2.9 on 2021-11-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211113_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='room',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.room'),
            preserve_default=False,
        ),
    ]
