# Generated by Django 3.2.9 on 2021-11-13 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sensor_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.room'),
        ),
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.user'),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.user'),
        ),
        migrations.AlterField(
            model_name='log',
            name='fingerprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.fingerprint'),
        ),
        migrations.AlterField(
            model_name='log',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.sensor'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.room'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='fine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.fine'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.student'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.room'),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.card'),
        ),
    ]
