# Generated by Django 3.2.9 on 2021-11-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211113_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreading',
            old_name='heating',
            new_name='gas',
        ),
    ]
